# Generated by Django 4.0.2 on 2023-03-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_completo_E', models.CharField(max_length=256)),
                ('Fecha_de_nacimiento_E', models.DateField()),
                ('Direccion_E', models.CharField(max_length=256)),
                ('Telefono_E', models.IntegerField(max_length=9)),
                ('Foto_E', models.ImageField(upload_to='')),
            ],
        ),
    ]
