# Generated by Django 4.0.2 on 2023-03-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista',
            name='id',
        ),
        migrations.AddField(
            model_name='especialista',
            name='ID_Especialista',
            field=models.IntegerField(default=111111, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Telefono_E',
            field=models.IntegerField(),
        ),
    ]
