# Generated by Django 4.0.2 on 2023-03-22 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0003_especialidad_especialista_especialidad_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Medica',
            fields=[
                ('ID_Area_Medica', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Nombre_Area_Medica', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Área Médica',
                'verbose_name_plural': 'Áreas Médicas',
            },
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Especialidad_P',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='AppReservaFacil.especialidad'),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='Area_Medica_F',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='AppReservaFacil.area_medica'),
        ),
    ]
