# Generated by Django 4.0.2 on 2023-03-24 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppReservaFacil', '0004_area_medica_alter_especialidad_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('ID_Cita', models.DateTimeField(primary_key=True, serialize=False, unique=True)),
                ('ID_Cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('ID_Especialista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='AppReservaFacil.especialista')),
            ],
        ),
    ]
