# Generated by Django 4.0.2 on 2023-03-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0005_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='Confirmacion_Cita',
            field=models.BooleanField(default=False),
        ),
    ]
