# Generated by Django 4.0.2 on 2023-03-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0007_cita_fecha_cita_alter_cita_id_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='Fecha_Cita',
        ),
        migrations.AlterField(
            model_name='cita',
            name='ID_Cita',
            field=models.DateTimeField(primary_key=True, serialize=False, unique=True),
        ),
    ]
