# Generated by Django 4.0.2 on 2023-04-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0008_remove_cita_fecha_cita_alter_cita_id_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAgregar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Empleado')),
                ('cargo', models.CharField(max_length=40, verbose_name='Cargo del Empleado')),
                ('rut', models.CharField(max_length=10, verbose_name='Rut del Empleado')),
                ('correo', models.CharField(max_length=40, verbose_name='sexo del Empleado')),
                ('telefonoCelular', models.CharField(max_length=10, verbose_name='telefono celular')),
                ('telefono', models.CharField(max_length=10, verbose_name='telefono fijo')),
                ('telefonoContacto', models.CharField(max_length=10, verbose_name='telefono de Contacto de Emergencia')),
            ],
        ),
        migrations.CreateModel(
            name='NuevoUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUser', models.CharField(max_length=50, verbose_name='Nombre usuario')),
                ('password', models.CharField(max_length=14, verbose_name='Password usuario')),
                ('password2', models.CharField(max_length=14, verbose_name='Password ')),
            ],
        ),
    ]
