# Generated by Django 4.0.2 on 2023-04-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0009_adminagregar_nuevousuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='Fecha_Cita',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='Hora_Cita',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
