# Generated by Django 4.0.2 on 2023-04-11 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppReservaFacil', '0010_cita_fecha_cita_cita_hora_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='Usuario_E',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
