# Generated by Django 4.0.2 on 2023-04-12 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0011_especialista_usuario_e'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminAgregar',
        ),
        migrations.DeleteModel(
            name='NuevoUsuarios',
        ),
        migrations.AddField(
            model_name='especialista',
            name='Especialidad_C',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Especialidad_C', to='AppReservaFacil.especialidad'),
        ),
        migrations.AddField(
            model_name='especialista',
            name='Especialidad_S',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Especialidad_S', to='AppReservaFacil.especialidad'),
        ),
        migrations.AddField(
            model_name='especialista',
            name='Especialidad_T',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Especialidad_T', to='AppReservaFacil.especialidad'),
        ),
        migrations.AddField(
            model_name='especialista',
            name='Rut',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='Sexo',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Direccion_E',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Especialidad_P',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Especialidad_P', to='AppReservaFacil.especialidad'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Fecha_de_nacimiento_E',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Foto_E',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Telefono_E',
            field=models.IntegerField(null=True),
        ),
    ]
