# Generated by Django 4.2 on 2023-04-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0012_delete_adminagregar_delete_nuevousuarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='Dia_Esp_C',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='Dia_Esp_P',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='Dia_Esp_S',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='Dia_Esp_T',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='Minutes_Esp_C',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='Minutes_Esp_P',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='Minutes_Esp_S',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='Minutes_Esp_T',
            field=models.IntegerField(null=True),
        ),
    ]
