# Generated by Django 4.2 on 2023-04-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0013_especialista_dia_esp_c_especialista_dia_esp_p_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='Dia_Esp_C',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Dia_Esp_P',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Dia_Esp_S',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Dia_Esp_T',
            field=models.BooleanField(null=True),
        ),
    ]
