<<<<<<< HEAD
# Generated by Django 4.0.2 on 2023-04-13 14:24
=======
# Generated by Django 4.2 on 2023-04-13 14:22
>>>>>>> Israel-branch

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0014_alter_especialista_dia_esp_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='Dia_Esp_C',
<<<<<<< HEAD
            field=models.CharField(max_length=60, null=True),
=======
            field=models.CharField(max_length=15, null=True),
>>>>>>> Israel-branch
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Dia_Esp_P',
<<<<<<< HEAD
            field=models.CharField(max_length=60, null=True),
=======
            field=models.CharField(max_length=15, null=True),
>>>>>>> Israel-branch
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Dia_Esp_S',
<<<<<<< HEAD
            field=models.CharField(max_length=60, null=True),
=======
            field=models.CharField(max_length=15, null=True),
>>>>>>> Israel-branch
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Dia_Esp_T',
<<<<<<< HEAD
            field=models.CharField(max_length=60, null=True),
=======
            field=models.CharField(max_length=15, null=True),
>>>>>>> Israel-branch
        ),
    ]
