# Generated by Django 4.0.2 on 2023-04-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0015_alter_especialista_dia_esp_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='Dia_Esp_C',
            field=models.CharField(choices=[('lun', 'Lunes'), ('mar', 'Martes'), ('mie', 'Miercoles'), ('jue', 'Jueves'), ('vie', 'Viernes'), ('sab', 'Sabado'), ('dom', 'Domingo')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Dia_Esp_P',
            field=models.CharField(choices=[('lun', 'Lunes'), ('mar', 'Martes'), ('mie', 'Miercoles'), ('jue', 'Jueves'), ('vie', 'Viernes'), ('sab', 'Sabado'), ('dom', 'Domingo')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Dia_Esp_S',
            field=models.CharField(choices=[('lun', 'Lunes'), ('mar', 'Martes'), ('mie', 'Miercoles'), ('jue', 'Jueves'), ('vie', 'Viernes'), ('sab', 'Sabado'), ('dom', 'Domingo')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Dia_Esp_T',
            field=models.CharField(choices=[('lun', 'Lunes'), ('mar', 'Martes'), ('mie', 'Miercoles'), ('jue', 'Jueves'), ('vie', 'Viernes'), ('sab', 'Sabado'), ('dom', 'Domingo')], max_length=60, null=True),
        ),
    ]
