# Generated by Django 4.0.2 on 2023-04-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0016_alter_especialista_dia_esp_c_and_more'),
        ('AppReservaFacil', '0017_alter_especialista_dia_esp_c_and_more'),
    ]

    operations = [
    ]
