# Generated by Django 4.0.2 on 2023-04-14 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppReservaFacil', '0018_merge_20230414_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='Dia_Esp_C',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('lun', 'Lunes'), ('mar', 'Martes'), ('mie', 'Miercoles'), ('jue', 'Jueves'), ('vie', 'Viernes'), ('sab', 'Sabado'), ('dom', 'Domingo')], default='jue', max_length=27),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Dia_Esp_P',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('lun', 'Lunes'), ('mar', 'Martes'), ('mie', 'Miercoles'), ('jue', 'Jueves'), ('vie', 'Viernes'), ('sab', 'Sabado'), ('dom', 'Domingo')], default='mar', max_length=27),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Dia_Esp_S',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('lun', 'Lunes'), ('mar', 'Martes'), ('mie', 'Miercoles'), ('jue', 'Jueves'), ('vie', 'Viernes'), ('sab', 'Sabado'), ('dom', 'Domingo')], default='mie', max_length=27),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Dia_Esp_T',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('lun', 'Lunes'), ('mar', 'Martes'), ('mie', 'Miercoles'), ('jue', 'Jueves'), ('vie', 'Viernes'), ('sab', 'Sabado'), ('dom', 'Domingo')], default='dom', max_length=27),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Telefono_E',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('ID_Operador', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Nombre_completo_O', models.CharField(max_length=256)),
                ('Rut', models.CharField(max_length=9, null=True)),
                ('Sexo', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=9, null=True)),
                ('Fecha_de_nacimiento_O', models.DateField(null=True)),
                ('Direccion_O', models.CharField(max_length=256, null=True)),
                ('Telefono_O', models.CharField(max_length=9, null=True)),
                ('Foto_O', models.ImageField(null=True, upload_to='')),
                ('Fecha_de_contrato_O', models.DateField(null=True)),
                ('Fecha_fin_de_contrato_O', models.DateField(null=True)),
                ('Usuario_O', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
