# Generated by Django 4.0.2 on 2023-04-20 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppReservaFacil', '0019_alter_especialista_dia_esp_c_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operador',
            options={'verbose_name': 'Operador', 'verbose_name_plural': 'Operadores'},
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('ID_Paciente', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Nombre_Paciente', models.CharField(max_length=256)),
                ('Rut', models.CharField(max_length=9)),
                ('Sexo', models.CharField(max_length=9, verbose_name=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')])),
                ('Fecha_de_nacimiento_P', models.DateField()),
                ('Direccion_P', models.CharField(max_length=256)),
                ('Telefono_P', models.CharField(max_length=9)),
                ('Usuario_P', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pracientes',
            },
        ),
    ]
