# Generated by Django 4.0.2 on 2023-04-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0020_mensaje_alter_operador_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialista',
            old_name='Minutes_Esp_C',
            new_name='Minutes_Esp_P_Dom',
        ),
        migrations.RenameField(
            model_name='especialista',
            old_name='Minutes_Esp_P',
            new_name='Minutes_Esp_P_Jue',
        ),
        migrations.RenameField(
            model_name='especialista',
            old_name='Minutes_Esp_S',
            new_name='Minutes_Esp_P_Lun',
        ),
        migrations.RenameField(
            model_name='especialista',
            old_name='Minutes_Esp_T',
            new_name='Minutes_Esp_P_Mar',
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='Dia_Esp_C',
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='Dia_Esp_T',
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='Especialidad_C',
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='Especialidad_T',
        ),
        migrations.AddField(
            model_name='especialista',
            name='Minutes_Esp_P_Mie',
            field=models.IntegerField(choices=[(15, '15 Minutos'), (30, '30 Minutos'), (45, '45 Minutos'), (60, '60 Minutos')], null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='Minutes_Esp_P_Sab',
            field=models.IntegerField(choices=[(15, '15 Minutos'), (30, '30 Minutos'), (45, '45 Minutos'), (60, '60 Minutos')], null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='Minutes_Esp_P_Vie',
            field=models.IntegerField(choices=[(15, '15 Minutos'), (30, '30 Minutos'), (45, '45 Minutos'), (60, '60 Minutos')], null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='Minutes_Esp_S_Dom',
            field=models.IntegerField(choices=[(15, '15 Minutos'), (30, '30 Minutos'), (45, '45 Minutos'), (60, '60 Minutos')], null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='Minutes_Esp_S_Jue',
            field=models.IntegerField(choices=[(15, '15 Minutos'), (30, '30 Minutos'), (45, '45 Minutos'), (60, '60 Minutos')], null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='Minutes_Esp_S_Lun',
            field=models.IntegerField(choices=[(15, '15 Minutos'), (30, '30 Minutos'), (45, '45 Minutos'), (60, '60 Minutos')], null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='Minutes_Esp_S_Mar',
            field=models.IntegerField(choices=[(15, '15 Minutos'), (30, '30 Minutos'), (45, '45 Minutos'), (60, '60 Minutos')], null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='Minutes_Esp_S_Mie',
            field=models.IntegerField(choices=[(15, '15 Minutos'), (30, '30 Minutos'), (45, '45 Minutos'), (60, '60 Minutos')], null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='Minutes_Esp_S_Sab',
            field=models.IntegerField(choices=[(15, '15 Minutos'), (30, '30 Minutos'), (45, '45 Minutos'), (60, '60 Minutos')], null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='Minutes_Esp_S_Vie',
            field=models.IntegerField(choices=[(15, '15 Minutos'), (30, '30 Minutos'), (45, '45 Minutos'), (60, '60 Minutos')], null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='fin_con_especialista',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='ini_con_especialista',
            field=models.DateField(null=True),
        ),
    ]
