# Generated by Django 4.0.2 on 2023-04-20 20:25

import AppReservaFacil.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppReservaFacil', '0021_rename_minutes_esp_c_especialista_minutes_esp_p_dom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='Foto_E',
            field=models.ImageField(null=True, upload_to=AppReservaFacil.models.foto_e_path),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Usuario_E',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
