# Generated by Django 4.0.2 on 2023-04-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0022_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Primer_Login',
            field=models.BooleanField(default=True),
        ),
    ]
