# Generated by Django 4.0.2 on 2023-04-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0023_paciente_primer_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Direccion_P',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Fecha_de_nacimiento_P',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Nombre_Paciente',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Rut',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Sexo',
            field=models.CharField(max_length=9, null=True, verbose_name=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Telefono_P',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
