# Generated by Django 4.0.2 on 2023-04-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0022_alter_especialista_foto_e_and_more'),
        ('AppReservaFacil', '0024_alter_paciente_direccion_p_and_more'),
    ]

    operations = [
    ]
