# Generated by Django 4.0.2 on 2023-04-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0025_merge_20230420_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Nombre_Paciente',
            field=models.CharField(max_length=256),
        ),
    ]
