# Generated by Django 4.0.2 on 2023-04-21 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppReservaFacil', '0026_alter_mensaje_options_alter_paciente_nombre_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='AppReservaFacil.chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
        migrations.AlterField(
            model_name='especialista',
            name='Foto_E',
            field=models.ImageField(null=True, upload_to='Paciente'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='Foto_O',
            field=models.ImageField(null=True, upload_to='Operador'),
        ),
        migrations.AddField(
            model_name='chat',
            name='esp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialista_chat', to='AppReservaFacil.especialista'),
        ),
        migrations.AddField(
            model_name='chat',
            name='ope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operador_chat', to='AppReservaFacil.operador'),
        ),
    ]
