# Generated by Django 4.0.2 on 2023-04-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0026_alter_mensaje_options_alter_paciente_nombre_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='Foto_E',
            field=models.ImageField(null=True, upload_to='Paciente'),
        ),
    ]
