# Generated by Django 4.0.2 on 2023-04-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0028_mensaje_remove_message_chat_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='Nombre_Destinatario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='Nombre_Remitente',
            field=models.CharField(max_length=100),
        ),
    ]
