# Generated by Django 4.0.2 on 2023-04-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0027_alter_especialista_foto_e'),
        ('AppReservaFacil', '0030_alter_mensaje_nombre_destinatario_and_more'),
    ]

    operations = [
    ]
