# Generated by Django 4.0.2 on 2023-04-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0031_merge_20230424_1109'),
        ('AppReservaFacil', '0031_merge_20230424_1206'),
    ]

    operations = [
    ]
