# Generated by Django 4.0.2 on 2023-04-25 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0031_merge_20230424_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha_Medica',
            fields=[
                ('ID_Ficha_Medica', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('RUT_Pac', models.CharField(max_length=9, null=True)),
                ('Nombre_Com_Pac', models.CharField(max_length=256)),
                ('Direccion_Pac', models.CharField(max_length=256, null=True)),
                ('Telefono_Pac', models.CharField(max_length=9, null=True)),
                ('Sis_Sal_Pac', models.CharField(choices=[('SegCom', 'Seguro Complementario'), ('ISAPRE', 'ISAPRE'), ('FONASA', 'FONASA'), ('FFAA', 'Fuerzas Armadas')], max_length=21, null=True)),
                ('Grupo_Sanguineo', models.CharField(choices=[('Amas', 'A+'), ('Omas', 'O+'), ('Bmas', 'B+'), ('ABmas', 'AB+'), ('Amenos', 'A-'), ('Omenos', 'O-'), ('Bmenos', 'B-'), ('ABmenos', 'AB-')], max_length=7, null=True)),
                ('Al_Antibioticos', models.BooleanField(null=True)),
                ('Antibioticos_TI', models.CharField(max_length=256)),
                ('Al_Medicamentos', models.BooleanField(null=True)),
                ('Medicamentos_TI', models.CharField(max_length=256)),
                ('Al_Alimentos', models.BooleanField(null=True)),
                ('Alimentos_TI', models.CharField(max_length=256)),
                ('Al_Ani_Ins', models.BooleanField(null=True)),
                ('Ani_Ins_TI', models.CharField(max_length=256)),
                ('Enf_Cronic', models.BooleanField(null=True)),
                ('Enf_Cronic_TI', models.CharField(max_length=256)),
                ('Med_Tom_Actu', models.TextField(max_length=256)),
            ],
            options={
                'verbose_name': 'Ficha Médica',
                'verbose_name_plural': 'Fichas Médicas',
            },
        ),
        migrations.CreateModel(
            name='Ficha_Cita',
            fields=[
                ('ID_Ficha_Cita', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Diagnostico_Cita', models.TextField(max_length=256)),
                ('Ficha_Medica_Pac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='AppReservaFacil.ficha_medica')),
                ('Nombre_Com_Esp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='AppReservaFacil.especialista')),
                ('RUT_Pac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='AppReservaFacil.paciente')),
            ],
            options={
                'verbose_name': 'Ficha Cita',
                'verbose_name_plural': 'Fichas Citas',
            },
        ),
    ]
