# Generated by Django 4.0.2 on 2023-04-25 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0032_merge_20230425_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaSinUsuario',
            fields=[
                ('ID_Cita', models.DateTimeField(primary_key=True, serialize=False, unique=True)),
                ('Fecha_Cita', models.CharField(max_length=20, null=True)),
                ('Hora_Cita', models.CharField(max_length=20, null=True)),
                ('Confirmacion_Cita', models.BooleanField(default=False)),
                ('Rut_Paciente', models.CharField(max_length=9)),
                ('Email_Contacto', models.EmailField(max_length=254, null=True)),
                ('Telefono_Contacto', models.IntegerField()),
                ('ID_Especialista', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AppReservaFacil.especialista')),
            ],
        ),
    ]
