# Generated by Django 4.0.2 on 2023-04-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0033_citasinusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citasinusuario',
            name='Telefono_Contacto',
            field=models.IntegerField(null=True),
        ),
    ]
