# Generated by Django 4.0.2 on 2023-04-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0032_ficha_medica_ficha_cita'),
        ('AppReservaFacil', '0034_alter_citasinusuario_telefono_contacto'),
    ]

    operations = [
    ]
