# Generated by Django 4.0.2 on 2023-04-25 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0035_merge_20230425_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citasinusuario',
            old_name='ID_Cita',
            new_name='ID_Cita_SU',
        ),
    ]
