# Generated by Django 4.0.2 on 2023-04-27 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0037_alter_ficha_medica_grupo_sanguineo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha_cita',
            name='Fecha_Cita',
            field=models.DateField(default='2023-06-23'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha_cita',
            name='Nombre_Com_Pac',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.RESTRICT, related_name='Nombre_com_Pac', to='AppReservaFacil.paciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ficha_cita',
            name='Ficha_Medica_Pac',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='AppReservaFacil.ficha_medica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ficha_cita',
            name='Nombre_Com_Esp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AppReservaFacil.especialista'),
        ),
        migrations.AlterField(
            model_name='ficha_cita',
            name='RUT_Pac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='RUT_Pac', to='AppReservaFacil.paciente'),
        ),
    ]
