# Generated by Django 4.0.2 on 2023-04-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0038_ficha_cita_fecha_cita_ficha_cita_nombre_com_pac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_cita',
            name='Nombre_Com_Esp',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='ficha_cita',
            name='Nombre_Com_Pac',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='ficha_cita',
            name='RUT_Pac',
            field=models.CharField(max_length=9),
        ),
    ]
