# Generated by Django 4.0.2 on 2023-04-27 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0039_alter_ficha_cita_nombre_com_esp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_cita',
            name='Nombre_Com_Esp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AppReservaFacil.especialista'),
        ),
        migrations.AlterField(
            model_name='ficha_cita',
            name='Nombre_Com_Pac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AppReservaFacil.paciente'),
        ),
    ]
