# Generated by Django 4.0.2 on 2023-04-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0038_cita_confirmacion_cita_operador_and_more'),
        ('AppReservaFacil', '0040_alter_ficha_cita_nombre_com_esp_and_more'),
    ]

    operations = [
    ]
