# Generated by Django 4.0.2 on 2023-04-27 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0037_rename_id_cita_su_citasinusuario_id_cita'),
        ('AppReservaFacil', '0040_alter_ficha_cita_nombre_com_esp_and_more'),
    ]

    operations = [
    ]
