# Generated by Django 4.0.2 on 2023-04-28 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0041_merge_20230427_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobrosEspecialistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monto_Esp_P', models.IntegerField(null=True)),
                ('Monto_Esp_S', models.IntegerField(null=True)),
                ('ID_Especialista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='AppReservaFacil.especialista')),
            ],
        ),
    ]
