# Generated by Django 4.0.2 on 2023-04-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0044_remove_cobrosespecialistas_nombre_completo_e'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrosespecialistas',
            name='Nombre_completo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
