# Generated by Django 4.0.2 on 2023-04-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0046_remove_cobrosespecialistas_nombre_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrosespecialistas',
            name='Nombre_completo_E',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
