# Generated by Django 4.0.2 on 2023-05-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0041_merge_20230427_1751'),
        ('AppReservaFacil', '0048_remove_cobrosespecialistas_nombre_completo_e'),
    ]

    operations = [
    ]
