# Generated by Django 4.0.2 on 2023-05-03 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0049_merge_20230503_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobrosespecialistas',
            name='ID_Especialista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppReservaFacil.especialista'),
        ),
    ]
