# Generated by Django 4.0.2 on 2023-05-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0050_cobro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='Monto',
            field=models.IntegerField(),
        ),
    ]
