# Generated by Django 4.0.2 on 2023-05-08 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0051_alter_cobro_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Boleta', models.IntegerField()),
                ('Rut_Pac_Boleta', models.CharField(max_length=9, null=True)),
                ('Monto_Boleta', models.IntegerField()),
                ('Fecha_Emision', models.DateField()),
                ('Metodo_Pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Debito', 'Debito'), ('Credito', 'Credito')], max_length=15)),
                ('Especialidad_Boleta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='AppReservaFacil.especialidad')),
                ('Especialista_Boleta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AppReservaFacil.especialista')),
            ],
        ),
    ]
