# Generated by Django 4.0.2 on 2023-05-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0052_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='Monto_Efectivo',
            field=models.IntegerField(null=True),
        ),
    ]
