# Generated by Django 4.0.2 on 2023-05-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0053_boleta_monto_efectivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='Arancel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='boleta',
            name='Num_Documento',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boleta',
            name='Tipo_atencion',
            field=models.CharField(choices=[('Particular', 'Particular'), ('Fonasa', 'Fonasa'), ('Isapre', 'Isapre'), ('Convenio', 'Convenio'), ('Otros', 'Otros')], max_length=15, null=True),
        ),
    ]
