# Generated by Django 4.0.2 on 2023-05-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0055_boleta_efectivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='Vuelto',
            field=models.IntegerField(null=True),
        ),
    ]
