# Generated by Django 4.0.2 on 2023-05-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0056_boleta_vuelto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='Monto_Efectivo',
        ),
    ]
