# Generated by Django 4.0.2 on 2023-05-11 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0057_remove_boleta_monto_efectivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_orden_examen', models.IntegerField()),
                ('Descripcion_examenes', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_receta', models.IntegerField()),
                ('Descripcion_receta', models.TextField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='ficha_cita',
            name='Examenes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='AppReservaFacil.examenes'),
        ),
        migrations.AddField(
            model_name='ficha_cita',
            name='Receta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='AppReservaFacil.receta'),
        ),
    ]
