# Generated by Django 4.0.2 on 2023-05-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0058_examenes_receta_ficha_cita_examenes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Examenes',
            new_name='Examene',
        ),
        migrations.RenameField(
            model_name='ficha_cita',
            old_name='Examenes',
            new_name='Examene',
        ),
    ]
