# Generated by Django 4.0.2 on 2023-05-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0050_alter_cobrosespecialistas_id_especialista'),
        ('AppReservaFacil', '0059_rename_examenes_examene_and_more'),
    ]

    operations = [
    ]
