# Generated by Django 4.0.2 on 2023-05-16 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0060_merge_20230512_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='Diagnostico_rec',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='Direccion_pac_receta',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='Edad_pac_receta',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='Especialidad_receta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='AppReservaFacil.especialidad'),
        ),
        migrations.AddField(
            model_name='receta',
            name='Especialista_receta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='AppReservaFacil.especialista'),
        ),
        migrations.AddField(
            model_name='receta',
            name='Nompre_paciente_receta',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='Rut_esp_receta',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='Rut_pac_receta',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='ficha_cita',
            name='Diagnostico_Cita',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='Descripcion_receta',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
