# Generated by Django 4.0.2 on 2023-05-18 14:26

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0061_receta_diagnostico_rec_receta_direccion_pac_receta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examene',
            name='Descripcion_examenes',
        ),
        migrations.AddField(
            model_name='examene',
            name='Examenes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Glucosa', 'Glucosa'), ('Nitrogeno_Ureico', 'Nitrogeno Ureico'), ('Urea', 'Urea'), ('Colesterol_total', 'Colesterol Total'), ('Acido_Urico', 'Acido Urico'), ('Proteinas_totales', 'Proteinas Totales'), ('Albuminca', 'Albúminca'), ('Globulinas', 'Globulinas'), ('Bilirrubina_total', 'Bilirrubina total'), ('Transaminasa_GOT', 'Transaminasa GOT'), ('Transaminada_GPT', 'Transaminada GPT'), ('Gammaglutamil_transferasa', ' Gammaglutamil transferasa'), ('Deshidrogenasa_lactica', 'Deshidrogenasa láctica'), ('Fosfatasas_alcalinas', 'Fosfatasas alcalinas'), ('Calcio_total', 'Calcio total'), ('Fosforo', 'Fósforo')], max_length=240, null=True),
        ),
    ]
