# Generated by Django 4.0.2 on 2023-05-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0062_remove_examene_descripcion_examenes_examene_examenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='examene',
            name='Diagnostico_orden',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='examene',
            name='Edad_pac_orden',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='examene',
            name='Fecha_nac_pac_orden',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='examene',
            name='Nombre_Medico_orden',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='examene',
            name='Nombre_pac_orden',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='examene',
            name='Prevision_pac_orden',
            field=models.CharField(choices=[('Particular', 'Particular'), ('Fonasa', 'Fonasa'), ('Isapre', 'Isapre'), ('Convenio', 'Convenio'), ('Otros', 'Otros')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='examene',
            name='Rut_Medico_orden',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='examene',
            name='Rut_pac_orden',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='examene',
            name='Servicio_pac_orden',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
