# Generated by Django 4.0.2 on 2023-05-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0063_examene_diagnostico_orden_examene_edad_pac_orden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examene',
            name='Fecha_nac_pac_orden',
            field=models.DateField(),
        ),
    ]
