# Generated by Django 4.0.2 on 2023-05-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0064_alter_examene_fecha_nac_pac_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examene',
            name='Fecha_nac_pac_orden',
            field=models.DateField(null=True),
        ),
    ]
