# Generated by Django 4.0.2 on 2023-05-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0067_alter_cita_metodo_pago_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='Metodo',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Debito', 'Debito'), ('Credito', 'Credito')], max_length=15, null=True),
        ),
    ]
