# Generated by Django 4.0.2 on 2023-05-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0068_cobro_metodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='Metodo',
            field=models.CharField(choices=[('Particular', 'Particular'), ('Fonasa', 'Fonasa'), ('Isapre', 'Isapre'), ('Convenio', 'Convenio'), ('Otros', 'Otros')], max_length=15, null=True),
        ),
    ]
