# Generated by Django 4.0.2 on 2023-05-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0069_alter_cobro_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasinusuario',
            name='Metodo_Pago_Cita',
            field=models.CharField(choices=[('Particular', 'Particular'), ('Fonasa', 'Fonasa'), ('Isapre', 'Isapre'), ('Convenio', 'Convenio'), ('Otros', 'Otros')], max_length=10, null=True),
        ),
    ]
