# Generated by Django 4.0.2 on 2023-06-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservaFacil', '0070_citasinusuario_metodo_pago_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examene',
            name='Examenes',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
